### ISSUE TITLE
"Skin Helper Services Error" Kodi 17.6

### ISSUE THREAD

**Issue by CNDVidel** [marcelveldt/script.skin.helper.service#118]
I am receiving a skin helper services error message in Kodi 17.6 when I try to use widgets to open apps on the main screen. The skin helper services addon is version 1.1.3 and is installed from the Kodi repository. 

This is what shows in the kodi.log file:

Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: cannot import name extend_dict
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.skin.helper.service/service.py", line 10, in <module>
                                                from resources.lib.main_service import MainService
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.skin.helper.service/resources/lib/main_service.py", line 13, in <module>
                                                from listitem_monitor import ListItemMonitor
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.skin.helper.service/resources/lib/listitem_monitor.py", line 13, in <module>
                                                from metadatautils import extend_dict, process_method_on_list
                                            ImportError: cannot import name extend_dict
                                            -->End of Python script error report<--
17:46:38.211 T:18446744072409329872   ERROR: ADDON: extension '' is not currently supported for service addon
17:46:53.857 T:18446744072387533120   ERROR: Previous line repeats 1 times.
17:46:53.857 T:18446744072387533120   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: cannot import name KodiDb
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.skin.helper.service/plugin.py", line 10, in <module>
                                                from resources.lib.plugin_content import PluginContent
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.skin.helper.service/resources/lib/plugin_content.py", line 17, in <module>
                                                from metadatautils import KodiDb, Tmdb, get_clean_image, process_method_on_list
                                            ImportError: cannot import name KodiDb
                                            -->End of Python script error report<--

**Comment by mrcottonmouth** [comment]
Me too

**Comment by CNDVidel** [comment]
I was finally able to find a working version (1.1.24) in the marcelveldt beta repo. I had to use the Git Browser addon from TVAddons to find the repo. All is working now.

**Comment by the-lazy-fox** [comment]
Any fix will be pushed to the kodi repo? :)
