### ISSUE TITLE
PythonToCppException

### ISSUE THREAD

**Issue by willhowlett** [marcelveldt/script.skin.helper.service#131]
Hi, I'm getting this error after setting up libreelec on a raspberry pi 4, using the Arctic Zephyr 2 skin and the latest version of skin helper service from your repo (1.1.24). Is there anything that can be suggested? Many thanks

```
2019-12-14 11:32:12.998 T:2373968752   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named backports.functools_lru_cache
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.skin.helper.widgets/plugin.py", line 9, in <module>
                                                import main
                                              File "/storage/.kodi/addons/script.skin.helper.widgets/resources/lib/main.py", line 17, in <module>
                                                from metadatautils import MetadataUtils
                                              File "/storage/.kodi/addons/script.module.metadatautils/lib/metadatautils.py", line 9, in <module>
                                                import helpers.kodi_constants as kodi_constants
                                              File "/storage/.kodi/addons/script.module.metadatautils/lib/helpers/kodi_constants.py", line 9, in <module>
                                                from utils import KODI_VERSION
                                              File "/storage/.kodi/addons/script.module.metadatautils/lib/helpers/utils.py", line 13, in <module>
                                                import arrow
                                              File "/storage/.kodi/addons/script.module.arrow/lib/arrow/__init__.py", line 3, in <module>
                                                from .arrow import Arrow
                                              File "/storage/.kodi/addons/script.module.arrow/lib/arrow/arrow.py", line 19, in <module>
                                                from arrow import util, locales, parser, formatter
                                              File "/storage/.kodi/addons/script.module.arrow/lib/arrow/parser.py", line 12, in <module>
                                                from backports.functools_lru_cache import lru_cache  # pragma: no cover
                                            ImportError: No module named backports.functools_lru_cache
                                            -->End of Python script error report<--
2019-12-14 11:32:13.003 T:2373968752   DEBUG: onExecutionDone(71, /storage/.kodi/addons/script.skin.helper.widgets/plugin.py)
2019-12-14 11:32:13.003 T:3011207184   DEBUG: ------ Window Init (DialogNotification.xml) ------
2019-12-14 11:32:13.015 T:2373968752    INFO: Python interpreter stopped
2019-12-14 11:32:13.015 T:2373968752   DEBUG: Thread LanguageInvoker 2373968752 terminating
2019-12-14 11:32:13.021 T:2843374448   ERROR: GetDirectory - Error getting plugin://script.skin.helper.widgets/?action=next&mediatype=episodes
```

**Comment by NanoWireDnB** [comment]
Had the same issue. It's actually the python lib "arrow" which is causing the trouble. A workaround for me is using an older version of arrow/the arrow-kodi-addon.

https://github.com/Razzeee/script.module.arrow/issues/2

**Comment by willhowlett** [comment]
@NanoWireDnB fsntastic thankyou. I’d just come across this post which also confirms it
https://www.reddit.com/r/Addons4Kodi/comments/ealwxs/skin_helper_service_widget_error

**Comment by willhowlett** [comment]
Looks like a new version of arrow is now available (but wasnt showing up yet for me)

As I'm impatient I manually installed
https://mirrors.kodi.tv/addons/leia/script.module.backports.functools_lru_cache/
then
https://mirrors.kodi.tv/addons/leia/script.module.arrow/ (15.5) which has fixed it

Thanks for the help :)
