### ISSUE TITLE
Addon not working; reports No module named bs4

### ISSUE THREAD

**Issue by hablaras** [marcelveldt/script.skin.helper.service#138]
Hi Marcel,

The addon is not working anymore in my Kodi 18.7 installation on a RPi 4.

The kodi.log file contains this error:
```
2020-12-09 09:03:18.029 T:2360332496 WARNING: Skin Helper Service --> Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/script.skin.helper.service/resources/lib/listitem_monitor.py", line 356, in set_listitem_details
                                                details = merge_dict(details, self.metadatautils.get_top250_rating(details["imdbnumber"]))
                                              File "/home/pi/.kodi/addons/script.module.metadatautils/lib/metadatautils.py", line 207, in get_top250_rating
                                                return self.imdb.get_top250_rating(imdb_id)
                                              File "/home/pi/.kodi/addons/script.module.metadatautils/lib/metadatautils.py", line 369, in imdb
                                                from helpers.imdb import Imdb
                                              File "/home/pi/.kodi/addons/script.module.metadatautils/lib/helpers/imdb.py", line 15, in <module>
                                                import bs4 as BeautifulSoup
                                            ImportError: No module named bs4
2020-12-09 09:03:18.029 T:2360332496   ERROR: Skin Helper Service --> Exception in resources.lib.listitem_monitor ! --> No module named bs4
```

The BeautifulSoup v3.2.1 addon is **enabled** under settings->systems->addon->manage dependencies.

Any idea what my cause this?

**Comment by Angelinas1** [comment]
Install from kodi repo or from .zip script.module.beautifulsoup4
https://mirrors.kodi.tv/addons/leia/script.module.beautifulsoup4/
