### ISSUE TITLE
Addon not working; reports global name 'sys' is not defined

### ISSUE THREAD

**Issue by hablaras** [marcelveldt/script.skin.helper.service#139]
Hi,

While #138 fixed the BeautifulSoup reference, I now get the following error for "global name 'sys' is not defined"

Am I missing another more recent version of any of the dependencies?

```
2020-12-10 00:34:12.753 T:2582626512  NOTICE: Skin Helper Widgets --> Backgroundservice started
2020-12-10 00:34:27.605 T:2187272400 WARNING: Skin Helper Service --> Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/script.skin.helper.service/resources/lib/listitem_monitor.py", line 336, in set_listitem_details
                                                efa = self.metadatautils.get_extrafanart(details["filenameandpath"])
                                              File "/home/pi/.kodi/addons/script.module.simplecache/lib/simplecache.py", line 305, in decorated
                                                result = func(*args, **kwargs)
                                              File "/home/pi/.kodi/addons/script.module.metadatautils/lib/metadatautils.py", line 44, in get_extrafanart
                                                return self._get_extrafanart(file_path)
                                              File "/home/pi/.kodi/addons/script.module.metadatautils/lib/helpers/extrafanart.py", line 40, in get_extrafanart
                                                if sys.version_info.major == 3:
                                            NameError: global name 'sys' is not defined
2020-12-10 00:34:27.605 T:2187272400   ERROR: Skin Helper Service --> Exception in resources.lib.listitem_monitor ! --> global name 'sys' is not defined
```

I have these versions installed:
- id="script.skin.helper.service" name="Skin Helper Service" version="1.1.31"
- id="script.module.metadatautils" name="Metadata and Artwork module" version="1.0.35"
- id="script.module.simplecache" name="Simple Cache Module" version="1.0.20"
- id="script.module.beautifulsoup" name="BeautifulSoup" version="3.2.1"
- id="script.module.beautifulsoup4" name="BeautifulSoup4" version="4.6.2"

Any help is appreciated, please let me know if you need any further logging or information.

Thanks for your help.

**Comment by hablaras** [comment]
I restarted Kodi again - which I did already before the reported error occurred - and now the message is gone and functionality is back. So I guess the ticket can be closed.
