### ISSUE TITLE
Error on boot of kodi on Raspberry pi2 and latest osmc......

### ISSUE THREAD

**Issue by DjDiabolik** [marcelveldt/script.skin.helper.service#140]
During very first of boot of osmc........ immediatelly after kodi boot up it's appears an error about script.skin.helper.service:

```
2021-01-10 14:37:44.477 T:1661559008  NOTICE: Skin Helper Widgets --> Backgroundservice started
2021-01-10 14:37:55.083 T:1669951712   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named parse
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/script.skin.helper.service/service.py", line 10, in <module>
                                                from resources.lib.main_service import MainService
                                              File "/home/osmc/.kodi/addons/script.skin.helper.service/resources/lib/main_service.py", line 15, in <module>
                                                from resources.lib.webservice import WebService
                                              File "/home/osmc/.kodi/addons/script.skin.helper.service/resources/lib/webservice.py", line 12, in <module>
                                                import cherrypy
                                              File "/home/osmc/.kodi/addons/script.module.cherrypy/lib/cherrypy/__init__.py", line 66, in <module>
                                                from ._cperror import (
                                              File "/home/osmc/.kodi/addons/script.module.cherrypy/lib/cherrypy/_cperror.py", line 123, in <module>
                                                import urllib.parse
                                            ImportError: No module named parse
                                            -->End of Python script error report<--
```

This errors appers on kodi.log......... i see and apparently both script it's update to latest version..... how i can fix this issue ?

**Comment by Angelinas1** [comment]
please update script.module.cherrypy in to version 12.0.1 that will fix issue with module for Python3.

**Comment by DjDiabolik** [comment]
mmmmmmmm.. i have updated both addons to current last version but apparently i know the nature of issue:
problably i have received upgrade for one of the two addons and the other it's stopped to works correctly.

I say this because today I turned my pi2 and all boot issue it's disappears.....

**Comment by Angelinas1** [comment]
I am glad that the problem has been solved
