### ISSUE TITLE
script.skin.helper.service only working for Kodi 19 / Python3?

### ISSUE THREAD

**Issue by hablaras** [marcelveldt/script.skin.helper.service#143]
Hi,

Small question: does script.skin.helper.service now only work for Kodi 19 / Python3? It is failing on my Kodi 18 / Python 2 libreelec installation because of the required xmbc.python version="3.0.0".

If so, is there a "latest" Python 2 version I can fall back to / download from this github?

**Comment by Angelinas1** [comment]
I start to change for Matrix, Last version for Leia is
`<addon id="script.skin.helper.service" name="Skin Helper Service" version="1.1.32" provider-name="marcelveldt">
    <requires>
	
        <import addon="xbmc.addon" version="12.0.0"/>
        <import addon="script.module.simplejson" version="3.3.0"/>
        <import addon="script.module.simplecache" version="1.0.0"/>
        <import addon="script.module.metadatautils" version="1.0.0"/>
        <import addon="script.module.cherrypy" version="17.0.0"/>
</requires>`
**but have small error for script.module.cherrypy",need to change addon.xml for this version="12.0.1",or download 
this version **
https://github.com/AnonTester/script.module.cherrypy/archive/refs/heads/master.zip

**Comment by hablaras** [comment]
Thanks for your response!

I've found an old 1.1.32 release and made the changes. It installs correctly:

2019-04-11 18:28:40.440 T:3012010592  NOTICE: ADDON: script.module.simplejson v3.16.1 installed
2019-04-11 18:28:40.440 T:3012010592  NOTICE: ADDON: script.skin.helper.service v1.1.32 installed
2019-04-11 18:28:40.440 T:3012010592  NOTICE: ADDON: script.module.metadatautils v1.0.39 installed

but I still get these two errors. They constantly occur together:

2021-04-27 21:47:50.796 T:2374292336 WARNING: script.module.metadatautils --> Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.module.metadatautils/lib/helpers/utils.py", line 130, in get_json
                                                result = json.loads(response.content.decode('utf-8', 'replace'))
                                              File "/storage/.kodi/addons/script.module.simplejson/lib/simplejson/__init__.py", line 538, in loads
                                                return _default_decoder.decode(s)
                                              File "/storage/.kodi/addons/script.module.simplejson/lib/simplejson/decoder.py", line 370, in decode
                                                obj, end = self.raw_decode(s)
                                              File "/storage/.kodi/addons/script.module.simplejson/lib/simplejson/decoder.py", line 400, in raw_decode
                                                return self.scan_once(s, idx=_w(s, idx).end())
                                              File "/storage/.kodi/addons/script.module.simplejson/lib/simplejson/scanner.py", line 79, in scan_once
                                                return _scan_once(string, idx)
                                              File "/storage/.kodi/addons/script.module.simplejson/lib/simplejson/scanner.py", line 70, in _scan_once
                                                raise JSONDecodeError(errmsg, string, idx)
                                            JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-04-27 21:47:50.797 T:2374292336   ERROR: script.module.metadatautils --> Exception in helpers.utils ! --> Expecting value: line 1 column 1 (char 0)
2021-04-27 21:47:50.802 T:2374292336 WARNING: Skin Helper Service --> Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.skin.helper.service/resources/lib/listitem_monitor.py", line 370, in set_listitem_details
                                                details["imdbnumber"]))
                                              File "/storage/.kodi/addons/script.module.metadatautils/lib/metadatautils.py", line 175, in get_animated_artwork
                                                imdb_id, manual_select=manual_select, ignore_cache=ignore_cache)
                                              File "/storage/.kodi/addons/script.module.simplecache/lib/simplecache.py", line 305, in decorated
                                                result = func(*args, **kwargs)
                                              File "/storage/.kodi/addons/script.module.metadatautils/lib/helpers/animatedart.py", line 53, in get_animated_artwork
                                                "animatedposter": self.poster(imdb_id, manual_select),
                                              File "/storage/.kodi/addons/script.module.metadatautils/lib/helpers/animatedart.py", line 63, in poster
                                                img = self.select_art(self.posters(imdb_id), manual_select, "poster")
                                              File "/storage/.kodi/addons/script.module.metadatautils/lib/helpers/animatedart.py", line 73, in posters
                                                return self.get_art(imdb_id, "posters")
                                              File "/storage/.kodi/addons/script.module.metadatautils/lib/helpers/animatedart.py", line 81, in get_art
                                                art_db = self.get_animatedart_db()
                                              File "/storage/.kodi/addons/script.module.metadatautils/lib/helpers/animatedart.py", line 95, in get_animatedart_db
                                                base_url = data.get("baseURL", "")
                                            AttributeError: 'NoneType' object has no attribute 'get'
2021-04-27 21:47:50.802 T:2374292336   ERROR: Skin Helper Service --> Exception in resources.lib.listitem_monitor ! --> 'NoneType' object has no attribute 'get'

It feels like going down a rabbit hole to get all dependencies fixed again for Leila, so - unless you know immediately what causes it - perhaps you should not spent too much time on this.

I guess I just have to wait until Libreelec releases the stable Matrix rpi4 version. The skin I use (Eminence MOD) cannot use the skin.helper service until then.

**Comment by Angelinas1** [comment]
I upload mine version for Leia can you test .
If all ok, i will upload at Marcel repo
this is link for *.zip
https://github.com/kodi-community-addons/repository.marcelveldt/raw/master/olderversions/script.module.metadatautils/script.module.metadatautils-1.0.40.zip

**Comment by hablaras** [comment]
Almost :)

Now I am back to this error: #138

I have both beautifulsoup versions installed:

2019-04-11 18:28:40.398 T:3011265120  NOTICE: ADDON: script.module.beautifulsoup v3.2.1 installed
2019-04-11 18:28:40.398 T:3011265120  NOTICE: ADDON: script.module.beautifulsoup4 v4.9.3 installed

2021-04-28 00:24:23.100 T:2431796080 WARNING: Skin Helper Service --> Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.skin.helper.service/resources/lib/listitem_monitor.py", line 353, in set_listitem_details
                                                details = merge_dict(details, self.metadatautils.get_top250_rating(details["imdbnumber"]))
                                              File "/storage/.kodi/addons/script.module.metadatautils/lib/metadatautils.py", line 207, in get_top250_rating
                                                return self.imdb.get_top250_rating(imdb_id)
                                              File "/storage/.kodi/addons/script.module.metadatautils/lib/metadatautils.py", line 369, in imdb
                                                from helpers.imdb import Imdb
                                              File "/storage/.kodi/addons/script.module.metadatautils/lib/helpers/imdb.py", line 15, in <module>
                                                import bs4 as BeautifulSoup
                                            ImportError: No module named bs4
2021-04-28 00:24:23.100 T:2431796080   ERROR: Skin Helper Service --> Exception in resources.lib.listitem_monitor ! --> No module named bs4

So I've added this to the "requires" element of script.module.metadatautils v1.0.40 addon.xml:

    <import addon="script.module.beautifulsoup4" version="4.9.3" />

And now it is working!

**Comment by Angelinas1** [comment]
!import BeautifulSoup"
insted "import bs4 as BeautifulSoup" is better solution.
If you find more error please write  here ....tnx

**Comment by Angelinas1** [comment]
Uploaded new version 1.0.40...for Leia
https://github.com/kodi-community-addons/repository.marcelveldt/commit/b977aa00df10007f921b3b5a4261847f1682a7ad
