### ISSUE TITLE
AttributeError: 'datetime.timedelta' object has no attribute 'timestamp' and ModuleNotFoundError: No module named 'PIL'

### ISSUE THREAD

**Issue by croneter** [marcelveldt/script.skin.helper.service#145]
I have also tried to use `arrow` in my [PlexKodiConnect-Kodi-Project](https://github.com/croneter/PlexKodiConnect), but stopped trying to do that as the exceptions below happened even more often (in `script.skin.helper.service` and NOT PKC! See https://github.com/croneter/PlexKodiConnect/issues/1458). It seemed to me that `import arrow` from several different Python instances were the culprit.
```
2021-06-06 10:39:38.192 T:5482    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'datetime.timedelta' object has no attribute 'timestamp'
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.skin.helper.service/service.py", line 10, in <module>
                                                       from resources.lib.main_service import MainService
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.skin.helper.service/resources/lib/main_service.py", line 16, in <module>
                                                       from metadatautils import MetadataUtils
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.metadatautils/lib/metadatautils.py", line 10, in <module>
                                                       import helpers.kodi_constants as kodi_constants
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.metadatautils/lib/helpers/kodi_constants.py", line 11, in <module>
                                                       from .utils import KODI_VERSION
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.metadatautils/lib/helpers/utils.py", line 13, in <module>
                                                       import arrow
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.arrow/lib/arrow/__init__.py", line 2, in <module>
                                                       from .api import get, now, utcnow
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.arrow/lib/arrow/api.py", line 12, in <module>
                                                       from arrow.arrow import TZ_EXPR, Arrow
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.arrow/lib/arrow/arrow.py", line 34, in <module>
                                                       from arrow import formatter, locales, parser, util
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.arrow/lib/arrow/parser.py", line 26, in <module>
                                                       from arrow.util import next_weekday, normalize_timestamp
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.arrow/lib/arrow/util.py", line 6, in <module>
                                                       from arrow.constants import (
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.arrow/lib/arrow/constants.py", line 16, in <module>
                                                       _MAX_TIMESTAMP = datetime.max.timestamp()
                                                   AttributeError: 'datetime.timedelta' object has no attribute 'timestamp'
                                                   -->End of Python script error report<--
```

Also, there seem to be related import-exceptions for `script.skin.helper.backgrounds`:
```
2021-06-06 10:39:24.814 T:5481  WARNING <general>: Skin Helper Backgrounds --> Exception details: Type: ModuleNotFoundError Value: No module named 'PIL' Traceback: Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.skin.helper.backgrounds/resources/lib/wallimages.py", line 24, in <module>
                                                       from PIL import Image
                                                   ModuleNotFoundError: No module named 'PIL'
```
and
```
2021-06-06 10:39:24.861 T:5481  WARNING <general>: Skin Helper Backgrounds --> Exception details: Type: ModuleNotFoundError Value: No module named 'Image' Traceback: Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.skin.helper.backgrounds/resources/lib/wallimages.py", line 24, in <module>
                                                       from PIL import Image
                                                   ModuleNotFoundError: No module named 'PIL'
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.skin.helper.backgrounds/resources/lib/wallimages.py", line 32, in <module>
                                                       import Image
                                                   ModuleNotFoundError: No module named 'Image'
```
DEBUG Log file:
[sanitized_kodi.log](https://github.com/kodi-community-addons/script.skin.helper.service/files/6603880/sanitized_kodi.log)

**Comment by Angelinas1** [comment]
For first error, I can do nothing....that is error from script.module.arrow, I try to change this too but without succes.
For second and third error......
Please test latest version script.skin.helper.backgrounds
https://github.com/kodi-community-addons/script.skin.helper.backgrounds/commit/ef927612512bf4df7a1161fc9d4e9983275ce194

**Comment by croneter** [comment]
Sorry, forgot to report back. Second and third error are fixed! But the first one still creeps up. Seems to be an issue with the Kodi Python implementation, if you ask me
