### ISSUE TITLE
AttributeError: 'MainService' object has no attribute 'webservice'

### ISSUE THREAD

**Issue by croneter** [marcelveldt/script.skin.helper.service#147]
```
2021-07-24 11:15:09.354 T:31037   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'MainService' object has no attribute 'webservice'
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.skin.helper.service/service.py", line 11, in <module>
                                                       MainService()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.skin.helper.service/resources/lib/main_service.py", line 54, in __init__
                                                       self.close()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.skin.helper.service/resources/lib/main_service.py", line 58, in close
                                                       self.webservice.stop()
                                                   AttributeError: 'MainService' object has no attribute 'webservice'
                                                   -->End of Python script error report<--
                                                   
```
Full log:
[kodi.old.log](https://github.com/kodi-community-addons/script.skin.helper.service/files/6872160/kodi.old.log)

**Comment by Angelinas1** [comment]
That isue was fixed 25 days ago....today I bump version on Marcel repo .
Please use version 1.1.39

**Comment by croneter** [comment]
Thanks!! Is there another Kodi repo that you're using preferably?
