### ISSUE TITLE
Multiprocessing and thus script.skin.helper.service broken on Google TV with Kodi 19.3: ImportError: This platform lacks a functioning sem_open implementation

### ISSUE THREAD

**Issue by croneter** [marcelveldt/script.skin.helper.service#150]
Kodi has issues with Python's multiprocessing. I even dropped multiprocessing entirely in PlexKodiConnect 😞 
```
2021-12-27 21:07:26.172 T:24347 WARNING <general>: script.skin.helper.widgets --> Exception details: Type: ImportError Value: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770. Traceback: Traceback (most recent call last):
                                                     File "/data/user/0/net.kodinerds.maven.kodi/cache/apk/assets/python3.8/lib/python3.8/multiprocessing/synchronize.py", line 28, in <module>
                                                       from _multiprocessing import SemLock, sem_unlink
                                                   ImportError: cannot import name 'sem_unlink' from '_multiprocessing' (unknown location)
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/net.kodinerds.maven.kodi/files/.kodi/addons/script.skin.helper.widgets/resources/lib/main.py", line 178, in show_widget_listing
                                                       all_items = getattr(media_class, action)()
                                                     File "/storage/emulated/0/Android/data/net.kodinerds.maven.kodi/files/.kodi/addons/script.skin.helper.widgets/resources/lib/media.py", line 163, in recent
                                                       all_items += self.albums.recent()
                                                     File "/storage/emulated/0/Android/data/net.kodinerds.maven.kodi/files/.kodi/addons/script.skin.helper.widgets/resources/lib/albums.py", line 55, in recent
                                                       return self.metadatautils.process_method_on_list(self.process_album, all_items)
                                                     File "/storage/emulated/0/Android/data/net.kodinerds.maven.kodi/files/.kodi/addons/script.module.metadatautils/lib/metadatautils.py", line 302, in process_method_on_list
                                                       return self._process_method_on_list(*args, **kwargs)
                                                     File "/storage/emulated/0/Android/data/net.kodinerds.maven.kodi/files/.kodi/addons/script.module.metadatautils/lib/helpers/utils.py", line 234, in process_method_on_list
                                                       pool = ThreadPool()
                                                     File "/data/user/0/net.kodinerds.maven.kodi/cache/apk/assets/python3.8/lib/python3.8/multiprocessing/pool.py", line 925, in __init__
                                                       Pool.__init__(self, processes, initializer, initargs)
                                                     File "/data/user/0/net.kodinerds.maven.kodi/cache/apk/assets/python3.8/lib/python3.8/multiprocessing/pool.py", line 196, in __init__
                                                       self._change_notifier = self._ctx.SimpleQueue()
                                                     File "/data/user/0/net.kodinerds.maven.kodi/cache/apk/assets/python3.8/lib/python3.8/multiprocessing/context.py", line 113, in SimpleQueue
                                                       return SimpleQueue(ctx=self.get_context())
                                                     File "/data/user/0/net.kodinerds.maven.kodi/cache/apk/assets/python3.8/lib/python3.8/multiprocessing/queues.py", line 336, in __init__
                                                       self._rlock = ctx.Lock()
                                                     File "/data/user/0/net.kodinerds.maven.kodi/cache/apk/assets/python3.8/lib/python3.8/multiprocessing/context.py", line 67, in Lock
                                                       from .synchronize import Lock
                                                     File "/data/user/0/net.kodinerds.maven.kodi/cache/apk/assets/python3.8/lib/python3.8/multiprocessing/synchronize.py", line 30, in <module>
                                                       raise ImportError("This platform lacks a functioning sem_open" +
                                                   ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.
                                                   
```
More detailed log: [kodi.log](https://github.com/kodi-community-addons/script.skin.helper.service/files/7781696/kodi.log)

**Comment by Angelinas1** [comment]
You use old version of script.module.metadatautils
-script.module.metadatautils v1.0.41 installed
Please update to version  v1.0.44 from marcel repo 

https://github.com/kodi-community-addons/repository.marcelveldt/raw/master/matrix/script.module.metadatautils/script.module.metadatautils-1.0.44.zip

**Comment by croneter** [comment]
Thanks a lot, that did the trick!
