### ISSUE TITLE
skin helper .35 issue - error resulted in kodi crashing

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/script.skin.helper.service#20]
wish i had debug on for this but here is the error that was logged right before kodi crashed.

running kodi 15.2 rc3 on win x64

16:59:17 T:9980  NOTICE: -->Python Interpreter Initialized<--
16:59:18 T:9980   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: too many values to unpack
                                            Traceback (most recent call last):
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.skin.helper.service\plugin.py", line 95, in <module>
                                                Main()
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.skin.helper.service\plugin.py", line 53, in **init**
                                                getRecentAlbums(limit)
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.skin.helper.service\resources\lib\PluginContent.py", line 503, in getRecentAlbums
                                                cdArt, LogoArt, BannerArt, extraFanArt, Info, TrackList = getMusicDetailsByDbId(item["albumid"], "albums")
                                            ValueError: too many values to unpack
                                            -->End of Python script error report<--
16:59:18 T:11848   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://script.skin.helper.service/?action=recentalbums&limit=100
16:59:18 T:6336  NOTICE: Thread LanguageInvoker start, auto delete: false
16:59:18 T:6336  NOTICE: -->Python Interpreter Initialized<--
16:59:19 T:6336   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: too many values to unpack
                                            Traceback (most recent call last):
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.skin.helper.service\plugin.py", line 95, in <module>
                                                Main()
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.skin.helper.service\plugin.py", line 55, in **init**
                                                getRecentSongs(limit)
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.skin.helper.service\resources\lib\PluginContent.py", line 594, in getRecentSongs
                                                cdArt, LogoArt, BannerArt, extraFanArt, Info, TrackList = getMusicDetailsByDbId(item["songid"], "songs")
                                            ValueError: too many values to unpack
                                            -->End of Python script error report<--
16:59:19 T:11848   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://script.skin.helper.service/?action=recentsongs&limit=100
16:59:19 T:5620  NOTICE: Thread LanguageInvoker start, auto delete: false

**Comment by marcelveldt** [comment]
should be fixed
