### ISSUE TITLE
osrandom engine already registered

### ISSUE THREAD

**Issue by Queuecumber** [marcelveldt/script.skin.helper.service#39]
I am getting a "skin helper service error" frequently (using the titan skin). When I examine the error log I see many errors with the text below. The only symptom I can see is that I can't seem to press the down arrow to open the power/settings tray on the home screen.

```
21:59:23 T:140335304931072   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: osrandom engine already registered
                                            Traceback (most recent call last):
                                              File "/home/mehrlich/.kodi/addons/script.skin.helper.service/service.py", line 5, in <module>
                                                from resources.lib.BackgroundsUpdater import BackgroundsUpdater
                                              File "/home/mehrlich/.kodi/addons/script.skin.helper.service/resources/lib/BackgroundsUpdater.py", line 9, in <module>
                                                import ArtworkUtils as artutils
                                              File "/home/mehrlich/.kodi/addons/script.skin.helper.service/resources/lib/ArtworkUtils.py", line 5, in <module>
                                                import requests
                                              File "/home/mehrlich/.kodi/addons/script.module.requests/lib/requests/__init__.py", line 53, in <module>
                                                from .packages.urllib3.contrib import pyopenssl
                                              File "/home/mehrlich/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 54, in <module>
                                                import OpenSSL.SSL
                                              File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
                                                from OpenSSL import rand, crypto, SSL
                                              File "/usr/lib/python2.7/dist-packages/OpenSSL/rand.py", line 11, in <module>
                                                from OpenSSL._util import (
                                              File "/usr/lib/python2.7/dist-packages/OpenSSL/_util.py", line 7, in <module>
                                                binding = Binding()
                                              File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 63, in __init__
                                                self._ensure_ffi_initialized()
                                              File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 95, in _ensure_ffi_initialized
                                                cls._register_osrandom_engine()
                                              File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 70, in _register_osrandom_engine
                                                raise RuntimeError("osrandom engine already registered")
                                            RuntimeError: osrandom engine already registered
                                            -->End of Python script error report<--
```

**Comment by marcelveldt** [comment]
strange, this eccor occurs in the requests module itself.

What platform are you running Kodi on ?

**Comment by Queuecumber** [comment]
Ubuntu Linux 15.10

**Comment by marcelveldt** [comment]
Hmm, not much I can do about it atm. The issue lies in the requests module that the script imports.
Many other reports about it, for example:

https://github.com/hippojay/plugin.video.plexbmc/issues/123
https://github.com/vonH/plugin.video.iplayerwww/issues/22
https://github.com/pyca/cryptography/issues/2287

The fix is already applied, now we have to wait untill the Kodi package for requests gets updated..
https://github.com/pyca/cryptography/pull/2293

**Comment by marcelveldt** [comment]
maybe this solution will also work for you:

http://emby.media/community/index.php?/topic/25735-emby-for-kodi-broken-no-sync/#entry251842

**Comment by Queuecumber** [comment]
Good catch, it was as simple as `sudo pip install --upgrade cryptography` no more error messages. Still can't navigate to the power menu using the keyboard though, I wonder if it is in a setting somewhere for titan that I missed.

**Comment by marcelveldt** [comment]
what homelayout are you using ?

**Comment by Queuecumber** [comment]
Just had a look, seems like it is the "Enable mouse/touchpad support" setting. When it is on, keyboard navigation on the homescreen won't work for opening the power menu tray. Not sure if this is by design or not, let me know if it isn't and I can open an issue with titan skin.

edit:
@marcelveldt just saw your message, enhanced all-in-one (I think is the name)
