### ISSUE TITLE
Utils.py throws KeyError exception

### ISSUE THREAD

**Issue by thebluepotato** [marcelveldt/script.skin.helper.service#46]
Sometimes when I finish an episode, Kodi crashes and throws the following log : 

```
20:42:05 T:584  NOTICE: CDVDMessageQueue::GetLevel() - can't determine level
20:42:06 T:12228  NOTICE: Previous line repeats 8 times.
20:42:06 T:12228 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
20:42:13 T:10644 WARNING: Previous line repeats 2 times.
20:42:13 T:10644  NOTICE: CDVDMessageQueue::GetLevel() - can't determine level
20:42:13 T:10644  NOTICE: CVideoPlayerAudio::Process - stream stalled
20:42:13 T:584  NOTICE: CVideoPlayer::OnExit()
20:42:13 T:584  NOTICE: VideoPlayer: eof, waiting for queues to empty
20:42:13 T:584  NOTICE: Closing stream player 1
20:42:13 T:584  NOTICE: CDVDMessageQueue(audio)::WaitUntilEmpty
20:42:13 T:584  NOTICE: Waiting for audio thread to exit
20:42:13 T:10644   ERROR: Got MSGQ_ABORT or MSGO_IS_ERROR return true
20:42:13 T:10644  NOTICE: thread end: CVideoPlayerAudio::OnExit()
20:42:13 T:584  NOTICE: Closing audio device
20:42:13 T:584  NOTICE: Deleting audio codec
20:42:13 T:584  NOTICE: Closing stream player 2
20:42:13 T:584  NOTICE: CDVDMessageQueue(video)::WaitUntilEmpty
20:42:13 T:584  NOTICE: waiting for video thread to exit
20:42:13 T:12228   ERROR: Got MSGQ_ABORT or MSGO_IS_ERROR return true
20:42:13 T:12228  NOTICE: thread end: video_thread
20:42:13 T:584  NOTICE: deleting video codec
20:42:13 T:584  NOTICE: Closing stream player 3
20:42:13 T:3052  NOTICE: CVideoPlayer::CloseFile()
20:42:13 T:3052  NOTICE: VideoPlayer: waiting for threads to exit
20:42:13 T:3052  NOTICE: VideoPlayer: finished waiting
20:42:13 T:3052  NOTICE: CVideoPlayer::CloseFile()
20:42:13 T:3052  NOTICE: VideoPlayer: waiting for threads to exit
20:42:13 T:3052  NOTICE: VideoPlayer: finished waiting
20:42:13 T:4988 WARNING: CWin32DirectSound::GetSpace - buffer underrun - W:7320, P:272, O:5288.
20:42:16 T:5812   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('item',)
                                            Traceback (most recent call last):
                                              File "C:\Users\Jonas\AppData\Roaming\Kodi\addons\script.skin.helper.service\resources\lib\KodiMonitor.py", line 29, in onNotification
                                                utils.resetVideoWidgetWindowProps(data)
                                              File "C:\Users\Jonas\AppData\Roaming\Kodi\addons\script.skin.helper.service\resources\lib\Utils.py", line 838, in resetVideoWidgetWindowProps
                                                type = data["item"]["type"]
                                            KeyError: ('item',)
                                            -->End of Python script error report<--
20:42:16 T:8292  NOTICE: [plugin.video.youtube] Running: YouTube (5.1.17) on Jarvis (17.0) with Python 2.7.10
20:42:17 T:11664  NOTICE: script.tv.show.next.aired: ### TV Show - Next Aired starting GUI proc (6.0.15)
20:42:17 T:14508 WARNING: CSkinInfo: failed to load skin settings
```

When a video is marked as watched after playback, I have the Trakt.TV addon fire up and ask for a rating. When a video is watched up to the last second, I have an addon fire up to show me the trailer for the next episode on youtube. I don't know if they're conflicting or if the issue is in your script but I'll drop that here anyway.
Tell me if you need any more info and I'll try to reproduce the bug with better debug logging enabled.

**Comment by marcelveldt** [comment]
Thanks for the catch, I've just fixed this.

**Comment by thebluepotato** [comment]
You are lightning-fast, thank you!
