### ISSUE TITLE
albumartistid keyerror

### ISSUE THREAD

**Issue by Rudd-O** [marcelveldt/script.skin.helper.service#57]
```
11:53:04 T:140314129835776   ERROR: Skin Helper Service --> ERROR in UpdateBackgrounds ! --> 'albumartistid'
11:53:04 T:140314129835776   ERROR: Traceback (most recent call last):
11:53:04 T:140314129835776   ERROR:   File "/home/user/.kodi/addons/script.skin.helper.service/resources/lib/BackgroundsUpdater.py", line 90, in run
11:53:04 T:140314129835776   ERROR:     self.UpdateBackgrounds()
11:53:04 T:140314129835776   ERROR:   File "/home/user/.kodi/addons/script.skin.helper.service/resources/lib/BackgroundsUpdater.py", line 455, in UpdateBackgrounds
11:53:04 T:140314129835776   ERROR:     self.setImageFromPath("SkinHelper.AllMusicSongsBackground","SkinHelper.AllMusicSongsBackground","",['AudioLibrary.GetSongs','{ "properties": ["title","fanart","artist","album","thumbnail"], "limits": {"end":250}, "sort": { "order": "ascending", "method": "random" } }'])
11:53:04 T:140314129835776   ERROR:   File "/home/user/.kodi/addons/script.skin.helper.service/resources/lib/BackgroundsUpdater.py", line 262, in setImageFromPath
11:53:04 T:140314129835776   ERROR:     media['art'] = artutils.getMusicArtwork(media['artist'][0], albumName=media['album'], trackName=media['label'])
11:53:04 T:140314129835776   ERROR:   File "/home/user/.kodi/addons/script.skin.helper.service/resources/lib/ArtworkUtils.py", line 1380, in getMusicArtwork
11:53:04 T:140314129835776   ERROR:     if json_response["artistid"] in song["albumartistid"] and not path2 and song.get("file"):
11:53:04 T:140314129835776   ERROR: KeyError: 'albumartistid'
```

**Comment by Rudd-O** [comment]
Hello?

**Comment by mgonzales71** [comment]
Hi,  I can't speak for Marcel but I am guessing that life can sidetrack you at times.  It was my understanding that as of like 6-8 months ago he is a new father / parent :smile:  Be patient I am certain there is a reason he has been busy.

KeyError is a missing dict (doesn't exist)

Make sure the artist info is correct and that is has scrapped properly into the library.

try resetting the cache from the helper script addon configuration panel in Kodi also.

**Comment by marcelveldt** [comment]
Hello @Rudd-O please use the Kodi forums to provide feedback or bugreports. I only use the Github issues for my own reference and to note down a todo list. That way I'll spot your report earlier.

What version of Kodi are you running ? The error is failing on a key that should exist at all times.

**Comment by Rudd-O** [comment]
16.1.  This was reported when I was using 16.0.

**Comment by marcelveldt** [comment]
This issue should be fixed in recent versions of the script. I'm not sure if that's already included in the Kodi repo though, an update to Kodi repo is pending.
