### ISSUE TITLE
Error decoding "local" movies imdbid

### ISSUE THREAD

**Issue by hablaras** [marcelveldt/script.skin.helper.service#77]
I have movies that are added with JustTheFilename scanner, that don't have an IMDB ID. For these movies information is trying to be retrieved from OMDBAPI, which of course fails.

(Here is some additional logging I added)

10:56:49.585 T:19348  NOTICE: Skin Helper Service --> Retrieving OMDBAPI info for ImdbId--> **20160216-2016-00241**  - contentType: movies - url: http://www.omdbapi.com/?t=20160216-2016-00241&y=2016&type=movie&plot=short&tomatoes=true&r=json
10:56:56.589 T:25892  NOTICE: Skin Helper Service --> Retrieving OMDBAPI info for ImdbId--> **20141109-1911-00138**  - contentType: movies - url: http://www.omdbapi.com/?t=20141109-1911-00138&y=2014&type=movie&plot=short&tomatoes=true&r=json
...
Then the following happens on line 1014 in ListItemMonitor. 

Code: 

omdbresult = json.loads(res.content.decode('utf-8','replace'))
            
10:57:14.338 T:19348  NOTICE: Skin Helper Service --> Retrieving OMDBAPI info for ImdbId--> **20160216-2016-00241**  - res: <Response [200]>
10:57:20.913 T:25892  NOTICE: Skin Helper Service --> Retrieving OMDBAPI info for ImdbId--> **20141109-1911-00138**  - res: <Response [503]>

They are http-response 200 and 503 respectively in these cases, because these IDs are bogus for the OMDBAPI.

Pasting the URL in the browser results in:
The service is unavailable.

And then you standard logging, which is what happens constantly for these movies:

10:57:20.913 T:25892   ERROR: Unhandled exception in thread started by
10:57:20.913 T:25892   ERROR: <bound method ListItemMonitor.setOmdbInfo of <ListItemMonitor(Thread-1, started 13068)>>
10:57:20.913 T:25892   ERROR: Traceback (most recent call last):
10:57:20.913 T:25892   ERROR:   File "C:\Users\hablaras\AppData\Roaming\Kodi\addons\script.skin.helper.service\resources\lib\ListItemMonitor.py", line 1016, in setOmdbInfo
10:57:20.915 T:25892   ERROR: omdbresult = json.loads(res.content.decode('utf-8','replace'))
10:57:20.915 T:25892   ERROR:   File "C:\Users\hablaras\AppData\Roaming\Kodi\addons\script.module.simplejson\lib\simplejson\__init__.py", line 488, in loads
10:57:20.916 T:25892   ERROR: return _default_decoder.decode(s)
10:57:20.916 T:25892   ERROR:   File "C:\Users\hablaras\AppData\Roaming\Kodi\addons\script.module.simplejson\lib\simplejson\decoder.py", line 370, in decode
10:57:20.916 T:25892   ERROR: obj, end = self.raw_decode(s)
10:57:20.916 T:25892   ERROR:   File "C:\Users\hablaras\AppData\Roaming\Kodi\addons\script.module.simplejson\lib\simplejson\decoder.py", line 389, in raw_decode
10:57:20.917 T:25892   ERROR: return self.scan_once(s, idx=_w(s, idx).end())
10:57:20.917 T:25892   ERROR:   File "C:\Users\hablaras\AppData\Roaming\Kodi\addons\script.module.simplejson\lib\simplejson\scanner.py", line 119, in scan_once
10:57:20.917 T:25892   ERROR: return _scan_once(string, idx)
10:57:20.917 T:25892   ERROR:   File "C:\Users\hablaras\AppData\Roaming\Kodi\addons\script.module.simplejson\lib\simplejson\scanner.py", line 115, in _scan_once
10:57:20.917 T:25892   ERROR: raise JSONDecodeError(errmsg, string, idx)
10:57:20.917 T:25892   ERROR: simplejson.scanner
10:57:20.917 T:25892   ERROR: .
10:57:20.917 T:25892   ERROR: JSONDecodeError
10:57:20.917 T:25892   ERROR: :
10:57:20.917 T:25892   ERROR: Expecting value: line 1 column 1 (char 0)

Would it be possible to to add a check on line 1013 just after this code to see if there is a valid HTTP response at all?

res = requests.get(url)

This would prevent all the ugly parsing errors.

**Comment by hablaras** [comment]
Hmm, I am now wondering if this was the latest version. This code is from 1.0.100 and 1.0.146 is the most recent I now see here. My RPi3 with OSMC is not updating to any version higher then 1.0.100...
