### ISSUE TITLE
script.skin.helper.service

### ISSUE THREAD

**Issue by abeksis** [marcelveldt/script.skin.helper.service#85]
08:29:54.897 T:1028   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named metadatautils
                                            Traceback (most recent call last):
                                              File "C:\Users\STARGRAF\AppData\Roaming\Kodi\addons\script.skin.helper.service\service.py", line 10, in <module>
                                                from resources.lib.main_service import MainService
                                              File "C:\Users\STARGRAF\AppData\Roaming\Kodi\addons\script.skin.helper.service\resources\lib\main_service.py", line 13, in <module>
                                                from listitem_monitor import ListItemMonitor
                                              File "C:\Users\STARGRAF\AppData\Roaming\Kodi\addons\script.skin.helper.service\resources\lib\listitem_monitor.py", line 13, in <module>
                                                from metadatautils import extend_dict, process_method_on_list
                                            ImportError: No module named metadatautils
                                            -->End of Python script error report<--

-------------------------

08:29:56.051 T:3276   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named simplecache
                                            Traceback (most recent call last):
                                              File "C:\Users\STARGRAF\AppData\Roaming\Kodi\addons\script.skin.helper.service\default.py", line 10, in <module>
                                                from resources.lib.main_module import MainModule
                                              File "C:\Users\STARGRAF\AppData\Roaming\Kodi\addons\script.skin.helper.service\resources\lib\main_module.py", line 16, in <module>
                                                from simplecache import SimpleCache
                                            ImportError: No module named simplecache
                                            -->End of Python script error report<--

**Comment by marcelveldt** [comment]
you have to install the addon through my repo or the kodi repo
