### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by hablaras** [marcelveldt/script.skin.helper.service#90]
Hi Marcel,

My default OSMC log for skin Eminence 2 MOD is currently filled with these kinds of messages. 

Do they ring a bell from the top of your head or do you need a debug log?

21:27:23.806 T:1723905008  NOTICE: Skin Helper Service --> **Skin Helper Service version 1.1.16** started
21:27:25.557 T:1400894448 WARNING: Skin Helper Service --> Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/script.skin.helper.service/resources/lib/listitem_monitor.py", line 314, in set_listitem_details
                                                details["year"], details["imdbnumber"], details["tvshowtitle"])
                                              File "/home/osmc/.kodi/addons/script.module.simplecache/lib/simplecache.py", line 284, in decorated
                                                result = func(*args, **kwargs)
                                              File "/home/osmc/.kodi/addons/script.module.metadatautils/lib/metadatautils.py", line 277, in get_imdbtvdb_id
                                                "", title, year, content_type).get("imdbnumber", "")
                                            AttributeError: 'NoneType' object has no attribute 'get'
21:27:25.557 T:1400894448   ERROR: Skin Helper Service --> Exception in resources.lib.listitem_monitor ! --> 'NoneType' object has no attribute 'get'

**Comment by marcelveldt** [comment]
Thanks for the report. I've located the issue in the code and applied a fix. This fix will be available in the next release of the skin helper add-on.
